mybatis-plus:
  #配置xml扫描路径
  mapper-locations: classpath:com/syl/eduservice/mapper/xml/*.xml
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 124.222.232.234:8848  #nacos服务地址
#feign:  #开启feign的熔断器功能
#  hystrix:
#    enabled: true

